# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test -Dtest=ParallelRunnerTest'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: PublishCucumberReport@1
  inputs:
    jsonDir: '$(System.DefaultWorkingDirectory)'
    outputPath: 'target/cucumber-html-reports/'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'target/cucumber-html-reports/'
    artifact: 'cucumber-html-reports'
    publishLocation: 'pipeline'